import { FunctionType } from '@aztec/foundation/abi';
import { Fr } from '@aztec/foundation/fields';
import { createDebugLogger } from '@aztec/foundation/log';
import { computeRootFromSiblingPath } from '../merkle/index.js';
import { computeArtifactFunctionTree, computeArtifactHash, computeArtifactHashPreimage, computeFunctionArtifactHash, computeFunctionMetadataHash, getArtifactMerkleTreeHasher, } from './artifact_hash.js';
import { getContractClassPrivateFunctionFromArtifact } from './contract_class.js';
import { computePrivateFunctionLeaf, computePrivateFunctionsTree } from './private_function.js';
/**
 * Creates a membership proof for a private function in a contract class, to be verified via `isValidPrivateFunctionMembershipProof`.
 * @param selector - Selector of the function to create the proof for.
 * @param artifact - Artifact of the contract class where the function is defined.
 */
export async function createPrivateFunctionMembershipProof(selector, artifact) {
    const log = createDebugLogger('aztec:circuits:function_membership_proof');
    // Locate private function definition and artifact
    const privateFunctions = artifact.functions
        .filter(fn => fn.functionType === FunctionType.PRIVATE)
        .map(getContractClassPrivateFunctionFromArtifact);
    const privateFunction = privateFunctions.find(fn => fn.selector.equals(selector));
    const privateFunctionArtifact = artifact.functions.find(fn => selector.equals(fn));
    if (!privateFunction || !privateFunctionArtifact) {
        throw new Error(`Private function with selector ${selector.toString()} not found`);
    }
    // Compute preimage for the artifact hash
    const { unconstrainedFunctionRoot: unconstrainedFunctionsArtifactTreeRoot, metadataHash: artifactMetadataHash } = computeArtifactHashPreimage(artifact);
    // We need two sibling paths because private function information is split across two trees:
    // The "private function tree" captures the selectors and verification keys, and is used in the kernel circuit for verifying the proof generated by the app circuit.
    const functionLeaf = await computePrivateFunctionLeaf(privateFunction);
    const functionsTree = await computePrivateFunctionsTree(privateFunctions);
    const functionsTreeLeafIndex = functionsTree.getIndex(functionLeaf);
    const functionsTreeSiblingPath = functionsTree.getSiblingPath(functionsTreeLeafIndex).map(Fr.fromBuffer);
    // And the "artifact tree" captures function bytecode and metadata, and is used by the pxe to check that its executing the code it's supposed to be executing, but it never goes into circuits.
    const functionMetadataHash = computeFunctionMetadataHash(privateFunctionArtifact);
    const functionArtifactHash = computeFunctionArtifactHash({ ...privateFunctionArtifact, functionMetadataHash });
    const artifactTree = computeArtifactFunctionTree(artifact, FunctionType.PRIVATE);
    const artifactTreeLeafIndex = artifactTree.getIndex(functionArtifactHash.toBuffer());
    const artifactTreeSiblingPath = artifactTree.getSiblingPath(artifactTreeLeafIndex).map(Fr.fromBuffer);
    log.debug(`Computed proof for private function with selector ${selector.toString()}`, {
        functionArtifactHash,
        functionMetadataHash,
        functionLeaf: '0x' + functionLeaf.toString('hex'),
        artifactMetadataHash,
        privateFunctionsTreeRoot: '0x' + functionsTree.root.toString('hex'),
        unconstrainedFunctionsArtifactTreeRoot,
        artifactFunctionTreeSiblingPath: artifactTreeSiblingPath.map(fr => fr.toString()).join(','),
        privateFunctionTreeSiblingPath: functionsTreeSiblingPath.map(fr => fr.toString()).join(','),
    });
    return {
        artifactTreeSiblingPath,
        artifactTreeLeafIndex,
        artifactMetadataHash,
        functionMetadataHash,
        unconstrainedFunctionsArtifactTreeRoot,
        privateFunctionTreeSiblingPath: functionsTreeSiblingPath,
        privateFunctionTreeLeafIndex: functionsTreeLeafIndex,
    };
}
/**
 * Verifies that a private function with a membership proof as emitted by the ClassRegisterer contract is valid,
 * as defined in the protocol specs at contract-deployment/classes:
 *
 * ```
 * // Load contract class from local db
 * contract_class = db.get_contract_class(contract_class_id)
 *
 * // Compute function leaf and assert it belongs to the private functions tree
 * function_leaf = pedersen([selector as Field, vk_hash], GENERATOR__FUNCTION_LEAF)
 * computed_private_function_tree_root = compute_root(function_leaf, private_function_tree_sibling_path)
 * assert computed_private_function_tree_root == contract_class.private_function_root
 *
 * // Compute artifact leaf and assert it belongs to the artifact
 * artifact_function_leaf = sha256(selector, metadata_hash, sha256(bytecode))
 * computed_artifact_private_function_tree_root = compute_root(artifact_function_leaf, artifact_function_tree_sibling_path)
 * computed_artifact_hash = sha256(computed_artifact_private_function_tree_root, unconstrained_functions_artifact_tree_root, artifact_metadata_hash)
 * assert computed_artifact_hash == contract_class.artifact_hash
 * ```
 * @param fn - Function to check membership proof for.
 * @param contractClass - In which contract class the function is expected to be.
 */
export async function isValidPrivateFunctionMembershipProof(fn, contractClass) {
    const log = createDebugLogger('aztec:circuits:function_membership_proof');
    // Check private function tree membership
    const functionLeaf = await computePrivateFunctionLeaf(fn);
    const computedPrivateFunctionTreeRoot = Fr.fromBuffer(await computeRootFromSiblingPath(functionLeaf, fn.privateFunctionTreeSiblingPath.map(fr => fr.toBuffer()), fn.privateFunctionTreeLeafIndex));
    if (!contractClass.privateFunctionsRoot.equals(computedPrivateFunctionTreeRoot)) {
        log.debug(`Private function tree root mismatch`, {
            expectedPrivateFunctionTreeRoot: contractClass.privateFunctionsRoot,
            computedPrivateFunctionTreeRoot: computedPrivateFunctionTreeRoot,
            computedFunctionLeaf: '0x' + functionLeaf.toString('hex'),
        });
        return false;
    }
    // Check artifact hash
    const functionArtifactHash = computeFunctionArtifactHash(fn);
    const computedArtifactPrivateFunctionTreeRoot = Fr.fromBuffer(await computeRootFromSiblingPath(functionArtifactHash.toBuffer(), fn.artifactTreeSiblingPath.map(fr => fr.toBuffer()), fn.artifactTreeLeafIndex, getArtifactMerkleTreeHasher()));
    const computedArtifactHash = computeArtifactHash({
        privateFunctionRoot: computedArtifactPrivateFunctionTreeRoot,
        unconstrainedFunctionRoot: fn.unconstrainedFunctionsArtifactTreeRoot,
        metadataHash: fn.artifactMetadataHash,
    });
    if (!contractClass.artifactHash.equals(computedArtifactHash)) {
        log.debug(`Artifact hash mismatch`, {
            expected: contractClass.artifactHash,
            computedArtifactHash,
            computedFunctionArtifactHash: functionArtifactHash,
            computedArtifactPrivateFunctionTreeRoot,
            unconstrainedFunctionRoot: fn.unconstrainedFunctionsArtifactTreeRoot,
            metadataHash: fn.artifactMetadataHash,
            artifactFunctionTreeSiblingPath: fn.artifactTreeSiblingPath.map(fr => fr.toString()).join(','),
        });
        return false;
    }
    return true;
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHJpdmF0ZV9mdW5jdGlvbl9tZW1iZXJzaGlwX3Byb29mLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vc3JjL2NvbnRyYWN0L3ByaXZhdGVfZnVuY3Rpb25fbWVtYmVyc2hpcF9wcm9vZi50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxPQUFPLEVBQWdELFlBQVksRUFBRSxNQUFNLHVCQUF1QixDQUFDO0FBQ25HLE9BQU8sRUFBRSxFQUFFLEVBQUUsTUFBTSwwQkFBMEIsQ0FBQztBQUM5QyxPQUFPLEVBQUUsaUJBQWlCLEVBQUUsTUFBTSx1QkFBdUIsQ0FBQztBQU8xRCxPQUFPLEVBQUUsMEJBQTBCLEVBQUUsTUFBTSxvQkFBb0IsQ0FBQztBQUNoRSxPQUFPLEVBQ0wsMkJBQTJCLEVBQzNCLG1CQUFtQixFQUNuQiwyQkFBMkIsRUFDM0IsMkJBQTJCLEVBQzNCLDJCQUEyQixFQUMzQiwyQkFBMkIsR0FDNUIsTUFBTSxvQkFBb0IsQ0FBQztBQUM1QixPQUFPLEVBQUUsMkNBQTJDLEVBQUUsTUFBTSxxQkFBcUIsQ0FBQztBQUNsRixPQUFPLEVBQUUsMEJBQTBCLEVBQUUsMkJBQTJCLEVBQUUsTUFBTSx1QkFBdUIsQ0FBQztBQUVoRzs7OztHQUlHO0FBQ0gsTUFBTSxDQUFDLEtBQUssVUFBVSxvQ0FBb0MsQ0FDeEQsUUFBMEIsRUFDMUIsUUFBMEI7SUFFMUIsTUFBTSxHQUFHLEdBQUcsaUJBQWlCLENBQUMsMENBQTBDLENBQUMsQ0FBQztJQUUxRSxrREFBa0Q7SUFDbEQsTUFBTSxnQkFBZ0IsR0FBRyxRQUFRLENBQUMsU0FBUztTQUN4QyxNQUFNLENBQUMsRUFBRSxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsWUFBWSxLQUFLLFlBQVksQ0FBQyxPQUFPLENBQUM7U0FDdEQsR0FBRyxDQUFDLDJDQUEyQyxDQUFDLENBQUM7SUFDcEQsTUFBTSxlQUFlLEdBQUcsZ0JBQWdCLENBQUMsSUFBSSxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsRUFBRSxDQUFDLFFBQVEsQ0FBQyxNQUFNLENBQUMsUUFBUSxDQUFDLENBQUMsQ0FBQztJQUNsRixNQUFNLHVCQUF1QixHQUFHLFFBQVEsQ0FBQyxTQUFTLENBQUMsSUFBSSxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsUUFBUSxDQUFDLE1BQU0sQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDO0lBQ25GLElBQUksQ0FBQyxlQUFlLElBQUksQ0FBQyx1QkFBdUIsRUFBRSxDQUFDO1FBQ2pELE1BQU0sSUFBSSxLQUFLLENBQUMsa0NBQWtDLFFBQVEsQ0FBQyxRQUFRLEVBQUUsWUFBWSxDQUFDLENBQUM7SUFDckYsQ0FBQztJQUVELHlDQUF5QztJQUN6QyxNQUFNLEVBQUUseUJBQXlCLEVBQUUsc0NBQXNDLEVBQUUsWUFBWSxFQUFFLG9CQUFvQixFQUFFLEdBQzdHLDJCQUEyQixDQUFDLFFBQVEsQ0FBQyxDQUFDO0lBRXhDLDRGQUE0RjtJQUM1RixvS0FBb0s7SUFDcEssTUFBTSxZQUFZLEdBQUcsTUFBTSwwQkFBMEIsQ0FBQyxlQUFlLENBQUMsQ0FBQztJQUN2RSxNQUFNLGFBQWEsR0FBRyxNQUFNLDJCQUEyQixDQUFDLGdCQUFnQixDQUFDLENBQUM7SUFDMUUsTUFBTSxzQkFBc0IsR0FBRyxhQUFhLENBQUMsUUFBUSxDQUFDLFlBQVksQ0FBQyxDQUFDO0lBQ3BFLE1BQU0sd0JBQXdCLEdBQUcsYUFBYSxDQUFDLGNBQWMsQ0FBQyxzQkFBc0IsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxFQUFFLENBQUMsVUFBVSxDQUFDLENBQUM7SUFFekcsK0xBQStMO0lBQy9MLE1BQU0sb0JBQW9CLEdBQUcsMkJBQTJCLENBQUMsdUJBQXVCLENBQUMsQ0FBQztJQUNsRixNQUFNLG9CQUFvQixHQUFHLDJCQUEyQixDQUFDLEVBQUUsR0FBRyx1QkFBdUIsRUFBRSxvQkFBb0IsRUFBRSxDQUFDLENBQUM7SUFDL0csTUFBTSxZQUFZLEdBQUcsMkJBQTJCLENBQUMsUUFBUSxFQUFFLFlBQVksQ0FBQyxPQUFPLENBQUUsQ0FBQztJQUNsRixNQUFNLHFCQUFxQixHQUFHLFlBQVksQ0FBQyxRQUFRLENBQUMsb0JBQW9CLENBQUMsUUFBUSxFQUFFLENBQUMsQ0FBQztJQUNyRixNQUFNLHVCQUF1QixHQUFHLFlBQVksQ0FBQyxjQUFjLENBQUMscUJBQXFCLENBQUMsQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDLFVBQVUsQ0FBQyxDQUFDO0lBRXRHLEdBQUcsQ0FBQyxLQUFLLENBQUMscURBQXFELFFBQVEsQ0FBQyxRQUFRLEVBQUUsRUFBRSxFQUFFO1FBQ3BGLG9CQUFvQjtRQUNwQixvQkFBb0I7UUFDcEIsWUFBWSxFQUFFLElBQUksR0FBRyxZQUFZLENBQUMsUUFBUSxDQUFDLEtBQUssQ0FBQztRQUNqRCxvQkFBb0I7UUFDcEIsd0JBQXdCLEVBQUUsSUFBSSxHQUFHLGFBQWEsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLEtBQUssQ0FBQztRQUNuRSxzQ0FBc0M7UUFDdEMsK0JBQStCLEVBQUUsdUJBQXVCLENBQUMsR0FBRyxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsRUFBRSxDQUFDLFFBQVEsRUFBRSxDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQztRQUMzRiw4QkFBOEIsRUFBRSx3QkFBd0IsQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsUUFBUSxFQUFFLENBQUMsQ0FBQyxJQUFJLENBQUMsR0FBRyxDQUFDO0tBQzVGLENBQUMsQ0FBQztJQUVILE9BQU87UUFDTCx1QkFBdUI7UUFDdkIscUJBQXFCO1FBQ3JCLG9CQUFvQjtRQUNwQixvQkFBb0I7UUFDcEIsc0NBQXNDO1FBQ3RDLDhCQUE4QixFQUFFLHdCQUF3QjtRQUN4RCw0QkFBNEIsRUFBRSxzQkFBc0I7S0FDckQsQ0FBQztBQUNKLENBQUM7QUFFRDs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0dBcUJHO0FBQ0gsTUFBTSxDQUFDLEtBQUssVUFBVSxxQ0FBcUMsQ0FDekQsRUFBZ0QsRUFDaEQsYUFBaUY7SUFFakYsTUFBTSxHQUFHLEdBQUcsaUJBQWlCLENBQUMsMENBQTBDLENBQUMsQ0FBQztJQUUxRSx5Q0FBeUM7SUFDekMsTUFBTSxZQUFZLEdBQUcsTUFBTSwwQkFBMEIsQ0FBQyxFQUFFLENBQUMsQ0FBQztJQUMxRCxNQUFNLCtCQUErQixHQUFHLEVBQUUsQ0FBQyxVQUFVLENBQ25ELE1BQU0sMEJBQTBCLENBQzlCLFlBQVksRUFDWixFQUFFLENBQUMsOEJBQThCLENBQUMsR0FBRyxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsRUFBRSxDQUFDLFFBQVEsRUFBRSxDQUFDLEVBQzFELEVBQUUsQ0FBQyw0QkFBNEIsQ0FDaEMsQ0FDRixDQUFDO0lBQ0YsSUFBSSxDQUFDLGFBQWEsQ0FBQyxvQkFBb0IsQ0FBQyxNQUFNLENBQUMsK0JBQStCLENBQUMsRUFBRSxDQUFDO1FBQ2hGLEdBQUcsQ0FBQyxLQUFLLENBQUMscUNBQXFDLEVBQUU7WUFDL0MsK0JBQStCLEVBQUUsYUFBYSxDQUFDLG9CQUFvQjtZQUNuRSwrQkFBK0IsRUFBRSwrQkFBK0I7WUFDaEUsb0JBQW9CLEVBQUUsSUFBSSxHQUFHLFlBQVksQ0FBQyxRQUFRLENBQUMsS0FBSyxDQUFDO1NBQzFELENBQUMsQ0FBQztRQUNILE9BQU8sS0FBSyxDQUFDO0lBQ2YsQ0FBQztJQUVELHNCQUFzQjtJQUN0QixNQUFNLG9CQUFvQixHQUFHLDJCQUEyQixDQUFDLEVBQUUsQ0FBQyxDQUFDO0lBQzdELE1BQU0sdUNBQXVDLEdBQUcsRUFBRSxDQUFDLFVBQVUsQ0FDM0QsTUFBTSwwQkFBMEIsQ0FDOUIsb0JBQW9CLENBQUMsUUFBUSxFQUFFLEVBQy9CLEVBQUUsQ0FBQyx1QkFBdUIsQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsUUFBUSxFQUFFLENBQUMsRUFDbkQsRUFBRSxDQUFDLHFCQUFxQixFQUN4QiwyQkFBMkIsRUFBRSxDQUM5QixDQUNGLENBQUM7SUFDRixNQUFNLG9CQUFvQixHQUFHLG1CQUFtQixDQUFDO1FBQy9DLG1CQUFtQixFQUFFLHVDQUF1QztRQUM1RCx5QkFBeUIsRUFBRSxFQUFFLENBQUMsc0NBQXNDO1FBQ3BFLFlBQVksRUFBRSxFQUFFLENBQUMsb0JBQW9CO0tBQ3RDLENBQUMsQ0FBQztJQUNILElBQUksQ0FBQyxhQUFhLENBQUMsWUFBWSxDQUFDLE1BQU0sQ0FBQyxvQkFBb0IsQ0FBQyxFQUFFLENBQUM7UUFDN0QsR0FBRyxDQUFDLEtBQUssQ0FBQyx3QkFBd0IsRUFBRTtZQUNsQyxRQUFRLEVBQUUsYUFBYSxDQUFDLFlBQVk7WUFDcEMsb0JBQW9CO1lBQ3BCLDRCQUE0QixFQUFFLG9CQUFvQjtZQUNsRCx1Q0FBdUM7WUFDdkMseUJBQXlCLEVBQUUsRUFBRSxDQUFDLHNDQUFzQztZQUNwRSxZQUFZLEVBQUUsRUFBRSxDQUFDLG9CQUFvQjtZQUNyQywrQkFBK0IsRUFBRSxFQUFFLENBQUMsdUJBQXVCLENBQUMsR0FBRyxDQUFDLEVBQUUsQ0FBQyxFQUFFLENBQUMsRUFBRSxDQUFDLFFBQVEsRUFBRSxDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQztTQUMvRixDQUFDLENBQUM7UUFDSCxPQUFPLEtBQUssQ0FBQztJQUNmLENBQUM7SUFFRCxPQUFPLElBQUksQ0FBQztBQUNkLENBQUMifQ==