// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import {
  MAX_KEY_VALIDATION_REQUESTS_PER_TX,
  MAX_NOTE_HASH_READ_REQUESTS_PER_TX,
  MAX_NULLIFIER_READ_REQUESTS_PER_TX,
} from '../../constants.gen.js';
import type { PrivateKernelResetCircuitPrivateInputs } from './private_kernel_reset_circuit_private_inputs.js';

export const PRIVATE_RESET_VARIANTS = {
  small: {
    NOTE_HASH_PENDING_AMOUNT: 8,
    NOTE_HASH_SETTLED_AMOUNT: 8,
    NULLIFIER_PENDING_AMOUNT: 8,
    NULLIFIER_SETTLED_AMOUNT: 8,
    NULLIFIER_KEYS: 8,
  },
  medium: {
    NOTE_HASH_PENDING_AMOUNT: 16,
    NOTE_HASH_SETTLED_AMOUNT: 16,
    NULLIFIER_PENDING_AMOUNT: 16,
    NULLIFIER_SETTLED_AMOUNT: 16,
    NULLIFIER_KEYS: 16,
  },
  big: {
    NOTE_HASH_PENDING_AMOUNT: 32,
    NOTE_HASH_SETTLED_AMOUNT: 32,
    NULLIFIER_PENDING_AMOUNT: 32,
    NULLIFIER_SETTLED_AMOUNT: 32,
    NULLIFIER_KEYS: 32,
  },
  full: {
    NOTE_HASH_PENDING_AMOUNT: MAX_NOTE_HASH_READ_REQUESTS_PER_TX,
    NOTE_HASH_SETTLED_AMOUNT: MAX_NOTE_HASH_READ_REQUESTS_PER_TX,
    NULLIFIER_PENDING_AMOUNT: MAX_NULLIFIER_READ_REQUESTS_PER_TX,
    NULLIFIER_SETTLED_AMOUNT: MAX_NULLIFIER_READ_REQUESTS_PER_TX,
    NULLIFIER_KEYS: MAX_KEY_VALIDATION_REQUESTS_PER_TX,
  },
} as const;

export type PrivateKernelResetTags = keyof typeof PRIVATE_RESET_VARIANTS;

export type PrivateKernelResetCircuitPrivateInputsVariants =
  | PrivateKernelResetCircuitPrivateInputs<8, 8, 8, 8, 8, 'small'>
  | PrivateKernelResetCircuitPrivateInputs<16, 16, 16, 16, 16, 'medium'>
  | PrivateKernelResetCircuitPrivateInputs<32, 32, 32, 32, 32, 'big'>
  | PrivateKernelResetCircuitPrivateInputs<
      typeof MAX_NOTE_HASH_READ_REQUESTS_PER_TX,
      typeof MAX_NOTE_HASH_READ_REQUESTS_PER_TX,
      typeof MAX_NULLIFIER_READ_REQUESTS_PER_TX,
      typeof MAX_NULLIFIER_READ_REQUESTS_PER_TX,
      typeof MAX_KEY_VALIDATION_REQUESTS_PER_TX,
      'full'
    >;
