/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  ContractNotes,
  ContractStorageLayout,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  EventSelector,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  L1EventPayload,
  NoirCompiledContract,
  NoteSelector,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
  loadContractArtifact,
} from '@aztec/aztec.js';

import AppSubscriptionContractArtifactJson from '../artifacts/app_subscription_contract-AppSubscription.json' assert { type: 'json' };

export const AppSubscriptionContractArtifact = loadContractArtifact(
  AppSubscriptionContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract AppSubscription;
 */
export class AppSubscriptionContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, AppSubscriptionContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, AppSubscriptionContract.artifact, wallet) as Promise<AppSubscriptionContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(
    wallet: Wallet,
    target_address: AztecAddressLike,
    subscription_recipient_address: AztecAddressLike,
    subscription_token_address: AztecAddressLike,
    subscription_price: FieldLike,
    gas_token_address: AztecAddressLike,
    gas_token_limit_per_tx: FieldLike,
  ) {
    return new DeployMethod<AppSubscriptionContract>(
      Fr.ZERO,
      wallet,
      AppSubscriptionContractArtifact,
      AppSubscriptionContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(
    publicKeysHash: Fr,
    wallet: Wallet,
    target_address: AztecAddressLike,
    subscription_recipient_address: AztecAddressLike,
    subscription_token_address: AztecAddressLike,
    subscription_price: FieldLike,
    gas_token_address: AztecAddressLike,
    gas_token_limit_per_tx: FieldLike,
  ) {
    return new DeployMethod<AppSubscriptionContract>(
      publicKeysHash,
      wallet,
      AppSubscriptionContractArtifact,
      AppSubscriptionContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AppSubscriptionContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<AppSubscriptionContract['methods'][M]>
  ) {
    return new DeployMethod<AppSubscriptionContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      AppSubscriptionContractArtifact,
      AppSubscriptionContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AppSubscriptionContractArtifact;
  }

  public static get storage(): ContractStorageLayout<'balances' | 'portal_address'> {
    return {
      balances: {
        slot: new Fr(1n),
      },
      portal_address: {
        slot: new Fr(2n),
      },
    } as ContractStorageLayout<'balances' | 'portal_address'>;
  }

  public static get notes(): ContractNotes<'TransparentNote' | 'TokenNote' | 'SubscriptionNote'> {
    return {
      TransparentNote: {
        id: new NoteSelector(1049878767),
      },
      TokenNote: {
        id: new NoteSelector(3992089675),
      },
      SubscriptionNote: {
        id: new NoteSelector(2695603941),
      },
    } as ContractNotes<'TransparentNote' | 'TokenNote' | 'SubscriptionNote'>;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {
    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      serialized_note: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** subscribe(subscriber_address: struct, nonce: field, expiry_block_number: field, tx_count: field) */
    subscribe: ((
      subscriber_address: AztecAddressLike,
      nonce: FieldLike,
      expiry_block_number: FieldLike,
      tx_count: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** is_initialized(subscriber_address: struct) */
    is_initialized: ((subscriber_address: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** constructor(target_address: struct, subscription_recipient_address: struct, subscription_token_address: struct, subscription_price: field, gas_token_address: struct, gas_token_limit_per_tx: field) */
    constructor: ((
      target_address: AztecAddressLike,
      subscription_recipient_address: AztecAddressLike,
      subscription_token_address: AztecAddressLike,
      subscription_price: FieldLike,
      gas_token_address: AztecAddressLike,
      gas_token_limit_per_tx: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** entrypoint(payload: struct, user_address: struct) */
    entrypoint: ((
      payload: {
        function_calls: {
          args_hash: FieldLike;
          function_selector: FunctionSelectorLike;
          target_address: AztecAddressLike;
          is_public: boolean;
          is_static: boolean;
        }[];
        nonce: FieldLike;
      },
      user_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;
  };
}
