/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  ContractNotes,
  ContractStorageLayout,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  EventSelector,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  L1EventPayload,
  NoirCompiledContract,
  NoteSelector,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
  loadContractArtifact,
} from '@aztec/aztec.js';

import CardGameContractArtifactJson from '../artifacts/card_game_contract-CardGame.json' assert { type: 'json' };

export const CardGameContractArtifact = loadContractArtifact(CardGameContractArtifactJson as NoirCompiledContract);

/**
 * Type-safe interface for contract CardGame;
 */
export class CardGameContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, CardGameContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, CardGameContract.artifact, wallet) as Promise<CardGameContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<CardGameContract>(
      Fr.ZERO,
      wallet,
      CardGameContractArtifact,
      CardGameContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet) {
    return new DeployMethod<CardGameContract>(
      publicKeysHash,
      wallet,
      CardGameContractArtifact,
      CardGameContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof CardGameContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<CardGameContract['methods'][M]>
  ) {
    return new DeployMethod<CardGameContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      CardGameContractArtifact,
      CardGameContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return CardGameContractArtifact;
  }

  public static get storage(): ContractStorageLayout<'collections' | 'game_decks' | 'games'> {
    return {
      collections: {
        slot: new Fr(1n),
      },
      game_decks: {
        slot: new Fr(2n),
      },
      games: {
        slot: new Fr(3n),
      },
    } as ContractStorageLayout<'collections' | 'game_decks' | 'games'>;
  }

  public static get notes(): ContractNotes<'ValueNote'> {
    return {
      ValueNote: {
        id: new NoteSelector(1900156023),
      },
    } as ContractNotes<'ValueNote'>;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {
    /** join_game(game: integer, cards_fields: array) */
    join_game: ((game: bigint | number, cards_fields: FieldLike[]) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      serialized_note: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** view_game(game: integer) */
    view_game: ((game: bigint | number) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** start_game(game: integer) */
    start_game: ((game: bigint | number) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** buy_pack(seed: field) */
    buy_pack: ((seed: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** play_card(game: integer, card: struct) */
    play_card: ((
      game: bigint | number,
      card: { strength: bigint | number; points: bigint | number },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** claim_cards(game: integer, cards_fields: array) */
    claim_cards: ((game: bigint | number, cards_fields: FieldLike[]) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** view_game_cards(game: integer, player: struct, offset: integer) */
    view_game_cards: ((
      game: bigint | number,
      player: AztecAddressLike,
      offset: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** view_collection_cards(owner: struct, offset: integer) */
    view_collection_cards: ((owner: AztecAddressLike, offset: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;
  };
}
