/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  ContractNotes,
  ContractStorageLayout,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  EventSelector,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  L1EventPayload,
  NoirCompiledContract,
  NoteSelector,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
  loadContractArtifact,
} from '@aztec/aztec.js';

import DelegatorContractArtifactJson from '../artifacts/delegator_contract-Delegator.json' assert { type: 'json' };

export const DelegatorContractArtifact = loadContractArtifact(DelegatorContractArtifactJson as NoirCompiledContract);

/**
 * Type-safe interface for contract Delegator;
 */
export class DelegatorContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, DelegatorContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, DelegatorContract.artifact, wallet) as Promise<DelegatorContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<DelegatorContract>(
      Fr.ZERO,
      wallet,
      DelegatorContractArtifact,
      DelegatorContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet) {
    return new DeployMethod<DelegatorContract>(
      publicKeysHash,
      wallet,
      DelegatorContractArtifact,
      DelegatorContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof DelegatorContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<DelegatorContract['methods'][M]>
  ) {
    return new DeployMethod<DelegatorContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      DelegatorContractArtifact,
      DelegatorContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return DelegatorContractArtifact;
  }

  public static get storage(): ContractStorageLayout<'current_value' | 'a_map_with_private_values'> {
    return {
      current_value: {
        slot: new Fr(1n),
      },
      a_map_with_private_values: {
        slot: new Fr(2n),
      },
    } as ContractStorageLayout<'current_value' | 'a_map_with_private_values'>;
  }

  public static get notes(): ContractNotes<'ValueNote'> {
    return {
      ValueNote: {
        id: new NoteSelector(1900156023),
      },
    } as ContractNotes<'ValueNote'>;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {
    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      serialized_note: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** private_delegate_set_value(target_contract: struct, value: field, owner: struct) */
    private_delegate_set_value: ((
      target_contract: AztecAddressLike,
      value: FieldLike,
      owner: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** public_delegate_set_value(target_contract: struct, value: field) */
    public_delegate_set_value: ((target_contract: AztecAddressLike, value: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** view_public_value() */
    view_public_value: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** enqueued_delegate_set_value(target_contract: struct, value: field) */
    enqueued_delegate_set_value: ((
      target_contract: AztecAddressLike,
      value: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** get_private_value(amount: field, owner: struct) */
    get_private_value: ((amount: FieldLike, owner: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;
  };
}
