/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  ContractNotes,
  ContractStorageLayout,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  EventSelector,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  L1EventPayload,
  NoirCompiledContract,
  NoteSelector,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
  loadContractArtifact,
} from '@aztec/aztec.js';

import GasTokenContractArtifactJson from '../artifacts/gas_token_contract-GasToken.json' assert { type: 'json' };

export const GasTokenContractArtifact = loadContractArtifact(GasTokenContractArtifactJson as NoirCompiledContract);

/**
 * Type-safe interface for contract GasToken;
 */
export class GasTokenContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, GasTokenContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, GasTokenContract.artifact, wallet) as Promise<GasTokenContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<GasTokenContract>(
      Fr.ZERO,
      wallet,
      GasTokenContractArtifact,
      GasTokenContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet) {
    return new DeployMethod<GasTokenContract>(
      publicKeysHash,
      wallet,
      GasTokenContractArtifact,
      GasTokenContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof GasTokenContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<GasTokenContract['methods'][M]>
  ) {
    return new DeployMethod<GasTokenContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      GasTokenContractArtifact,
      GasTokenContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return GasTokenContractArtifact;
  }

  public static get storage(): ContractStorageLayout<'balances' | 'portal_address'> {
    return {
      balances: {
        slot: new Fr(1n),
      },
      portal_address: {
        slot: new Fr(2n),
      },
    } as ContractStorageLayout<'balances' | 'portal_address'>;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {
    /** claim_public(to: struct, amount: field, secret: field, leaf_index: field) */
    claim_public: ((
      to: AztecAddressLike,
      amount: FieldLike,
      secret: FieldLike,
      leaf_index: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** set_portal(portal_address: struct) */
    set_portal: ((portal_address: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deploy(artifact_hash: field, private_functions_root: field, public_bytecode_commitment: field, portal_address: struct) */
    deploy: ((
      artifact_hash: FieldLike,
      private_functions_root: FieldLike,
      public_bytecode_commitment: FieldLike,
      portal_address: EthAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      serialized_note: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** mint_public(to: struct, amount: field) */
    mint_public: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** claim(to: struct, amount: field, secret: field) */
    claim: ((to: AztecAddressLike, amount: FieldLike, secret: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** check_balance(fee_limit: field) */
    check_balance: ((fee_limit: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** balance_of_public(owner: struct) */
    balance_of_public: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
