/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  ContractNotes,
  ContractStorageLayout,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  EventSelector,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  L1EventPayload,
  NoirCompiledContract,
  NoteSelector,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
  loadContractArtifact,
} from '@aztec/aztec.js';

import ImportTestContractArtifactJson from '../artifacts/import_test_contract-ImportTest.json' assert { type: 'json' };

export const ImportTestContractArtifact = loadContractArtifact(ImportTestContractArtifactJson as NoirCompiledContract);

/**
 * Type-safe interface for contract ImportTest;
 */
export class ImportTestContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, ImportTestContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, ImportTestContract.artifact, wallet) as Promise<ImportTestContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<ImportTestContract>(
      Fr.ZERO,
      wallet,
      ImportTestContractArtifact,
      ImportTestContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet) {
    return new DeployMethod<ImportTestContract>(
      publicKeysHash,
      wallet,
      ImportTestContractArtifact,
      ImportTestContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ImportTestContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<ImportTestContract['methods'][M]>
  ) {
    return new DeployMethod<ImportTestContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      ImportTestContractArtifact,
      ImportTestContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ImportTestContractArtifact;
  }

  public static get storage(): ContractStorageLayout<'example_constant' | 'example_set'> {
    return {
      example_constant: {
        slot: new Fr(1n),
      },
      example_set: {
        slot: new Fr(2n),
      },
    } as ContractStorageLayout<'example_constant' | 'example_set'>;
  }

  public static get notes(): ContractNotes<'ValueNote' | 'TestNote'> {
    return {
      ValueNote: {
        id: new NoteSelector(1900156023),
      },
      TestNote: {
        id: new NoteSelector(1541719451),
      },
    } as ContractNotes<'ValueNote' | 'TestNote'>;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {
    /** pub_call_public_fn(target: struct) */
    pub_call_public_fn: ((target: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      serialized_note: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** call_no_args(target: struct) */
    call_no_args: ((target: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** main_contract(target: struct) */
    main_contract: ((target: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** call_public_fn(target: struct) */
    call_public_fn: ((target: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
