/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  ContractNotes,
  ContractStorageLayout,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  EventSelector,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  L1EventPayload,
  NoirCompiledContract,
  NoteSelector,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
  loadContractArtifact,
} from '@aztec/aztec.js';

import KeyRegistryContractArtifactJson from '../artifacts/key_registry_contract-KeyRegistry.json' assert { type: 'json' };

export const KeyRegistryContractArtifact = loadContractArtifact(
  KeyRegistryContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract KeyRegistry;
 */
export class KeyRegistryContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, KeyRegistryContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, KeyRegistryContract.artifact, wallet) as Promise<KeyRegistryContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<KeyRegistryContract>(
      Fr.ZERO,
      wallet,
      KeyRegistryContractArtifact,
      KeyRegistryContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet) {
    return new DeployMethod<KeyRegistryContract>(
      publicKeysHash,
      wallet,
      KeyRegistryContractArtifact,
      KeyRegistryContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof KeyRegistryContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<KeyRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<KeyRegistryContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      KeyRegistryContractArtifact,
      KeyRegistryContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return KeyRegistryContractArtifact;
  }

  public static get storage(): ContractStorageLayout<
    | 'npk_m_x_registry'
    | 'npk_m_y_registry'
    | 'ivpk_m_x_registry'
    | 'ivpk_m_y_registry'
    | 'ovpk_m_x_registry'
    | 'ovpk_m_y_registry'
    | 'tpk_m_x_registry'
    | 'tpk_m_y_registry'
  > {
    return {
      npk_m_x_registry: {
        slot: new Fr(1n),
      },
      npk_m_y_registry: {
        slot: new Fr(2n),
      },
      ivpk_m_x_registry: {
        slot: new Fr(3n),
      },
      ivpk_m_y_registry: {
        slot: new Fr(4n),
      },
      ovpk_m_x_registry: {
        slot: new Fr(5n),
      },
      ovpk_m_y_registry: {
        slot: new Fr(6n),
      },
      tpk_m_x_registry: {
        slot: new Fr(7n),
      },
      tpk_m_y_registry: {
        slot: new Fr(8n),
      },
    } as ContractStorageLayout<
      | 'npk_m_x_registry'
      | 'npk_m_y_registry'
      | 'ivpk_m_x_registry'
      | 'ivpk_m_y_registry'
      | 'ovpk_m_x_registry'
      | 'ovpk_m_y_registry'
      | 'tpk_m_x_registry'
      | 'tpk_m_y_registry'
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {
    /** rotate_npk_m(address: struct, new_npk_m: struct, nonce: field) */
    rotate_npk_m: ((
      address: AztecAddressLike,
      new_npk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean },
      nonce: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      serialized_note: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** register_npk_and_ivpk(address: struct, partial_address: struct, keys: struct) */
    register_npk_and_ivpk: ((
      address: AztecAddressLike,
      partial_address: WrappedFieldLike,
      keys: {
        npk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean };
        ivpk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean };
        ovpk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean };
        tpk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean };
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** register_ovpk_and_tpk(address: struct, partial_address: struct, keys: struct) */
    register_ovpk_and_tpk: ((
      address: AztecAddressLike,
      partial_address: WrappedFieldLike,
      keys: {
        npk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean };
        ivpk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean };
        ovpk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean };
        tpk_m: { x: FieldLike; y: FieldLike; is_infinite: boolean };
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;
  };
}
