/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  ContractNotes,
  ContractStorageLayout,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  EventSelector,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  L1EventPayload,
  NoirCompiledContract,
  NoteSelector,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
  loadContractArtifact,
} from '@aztec/aztec.js';

import LendingContractArtifactJson from '../artifacts/lending_contract-Lending.json' assert { type: 'json' };

export const LendingContractArtifact = loadContractArtifact(LendingContractArtifactJson as NoirCompiledContract);

/**
 * Type-safe interface for contract Lending;
 */
export class LendingContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, LendingContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, LendingContract.artifact, wallet) as Promise<LendingContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<LendingContract>(
      Fr.ZERO,
      wallet,
      LendingContractArtifact,
      LendingContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet) {
    return new DeployMethod<LendingContract>(
      publicKeysHash,
      wallet,
      LendingContractArtifact,
      LendingContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof LendingContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<LendingContract['methods'][M]>
  ) {
    return new DeployMethod<LendingContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      LendingContractArtifact,
      LendingContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return LendingContractArtifact;
  }

  public static get storage(): ContractStorageLayout<'assets'> {
    return {
      assets: {
        slot: new Fr(1n),
      },
    } as ContractStorageLayout<'assets'>;
  }

  public static get notes(): ContractNotes<'TransparentNote' | 'TokenNote'> {
    return {
      TransparentNote: {
        id: new NoteSelector(1049878767),
      },
      TokenNote: {
        id: new NoteSelector(3992089675),
      },
    } as ContractNotes<'TransparentNote' | 'TokenNote'>;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {
    /** update_accumulator() */
    update_accumulator: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** borrow_public(to: struct, amount: field) */
    borrow_public: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** deposit_public(amount: field, nonce: field, on_behalf_of: field, collateral_asset: struct) */
    deposit_public: ((
      amount: FieldLike,
      nonce: FieldLike,
      on_behalf_of: FieldLike,
      collateral_asset: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** withdraw_private(secret: field, to: struct, amount: field) */
    withdraw_private: ((secret: FieldLike, to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_assets() */
    get_assets: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_position(owner: struct) */
    get_position: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_asset(asset_id: field) */
    get_asset: ((asset_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit_private(from: struct, amount: field, nonce: field, secret: field, on_behalf_of: field, collateral_asset: struct) */
    deposit_private: ((
      from: AztecAddressLike,
      amount: FieldLike,
      nonce: FieldLike,
      secret: FieldLike,
      on_behalf_of: FieldLike,
      collateral_asset: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** repay_private(from: struct, amount: field, nonce: field, secret: field, on_behalf_of: field, stable_coin: struct) */
    repay_private: ((
      from: AztecAddressLike,
      amount: FieldLike,
      nonce: FieldLike,
      secret: FieldLike,
      on_behalf_of: FieldLike,
      stable_coin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** init(oracle: struct, loan_to_value: field, collateral_asset: struct, stable_coin: struct) */
    init: ((
      oracle: AztecAddressLike,
      loan_to_value: FieldLike,
      collateral_asset: AztecAddressLike,
      stable_coin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** withdraw_public(to: struct, amount: field) */
    withdraw_public: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** borrow_private(secret: field, to: struct, amount: field) */
    borrow_private: ((secret: FieldLike, to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** repay_public(amount: field, nonce: field, owner: struct, stable_coin: struct) */
    repay_public: ((
      amount: FieldLike,
      nonce: FieldLike,
      owner: AztecAddressLike,
      stable_coin: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      serialized_note: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;
  };
}
